### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lukioc** [samartzidis/WinAppleKey#65]
1

**Comment by samartzidis** [comment]
Thanks for your good words @lukioc :) I do not think that there was any direct safety or security with WinAppleKey itself, but rather indirectly; with having to run Windows in test mode, plus due to the Microsoft driver signing restrictions acting as a blocker for any further development and evolution.

magicstick.io is an attempt to use a microcontroller for the same task due to its extra simplicity ultra-low cost and inherent advantages as a simple keyboard controller.
